name: diem_danh_sv
description: "A student attendance tracking application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  fl_chart: ^0.66.1
  qr_code_scanner:
    path: local_plugins/qr_code_scanner
  intl: ^0.19.0
  sqflite: ^2.3.2
  path: ^1.8.3
  http: ^1.2.0
  google_fonts: ^6.1.0
  dio: ^5.8.0+1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  go_router: ^15.1.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  window_manager: ^0.4.3
  geolocator: ^10.0.1
  lottie: ^3.3.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/animations/
